# Generated by Django 5.2.8 on 2025-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, default='', max_length=1000)),
                ('paid', models.BooleanField(default=False)),
                ('checkout_url', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
